version: '3.8'

services:
  k-rangers-ai:
    build: .
    container_name: k-rangers-ai-server
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8001/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
