# ================================================
# COMMON Profile Settings
# ================================================
spring:
  profiles:
    # 기본 활성화 프로필을 'local'로 설정합니다.
    # 이 값은 실행 시 환경 변수나 JVM 옵션으로 덮어쓸 수 있습니다. (예: -Dspring.profiles.active=prod)
    active: ${PROFILE:local}

  application:
    name: K-Rangers-Backend

  # JPA 관련 공통 설정 (필요 시)
  jpa:
    show-sql: true # SQL 로그는 모든 환경에서 보도록 설정

# ================================================
# API Keys & Server Port (모든 환경 공통)
# ================================================
ai:
  server:
    url: ${AI_SERVER_URL:http://localhost:8001}
  openai:
    api-key: ${OPENAI_API_KEY}

kakao:
  api:
    key: ${KAKAO_API_KEY}
    url: "https://dapi.kakao.com/v2/local/search/address.json"

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 9000
