spring:
  profiles:
    active: ${PROFILE:local}

  application:
    name: K-Rangers-Backend
  jpa:
    show-sql: true
ai:
  server:
    url: ${AI_SERVER_URL:http://localhost:8001}
  openai:
    api-key: ${OPENAI_API_KEY}

kakao:
  api:
    key: ${KAKAO_API_KEY}
    url: "https://dapi.kakao.com/v2/local/search/address.json"

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 9000
