ai:
  server:
    url: ${AI_SERVER_URL:http://localhost:8001}
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:activity-server;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active: ${PROFILE}
  application:
    name: K-Rangers-Backend
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4.1-nano-2025-04-14
kakao:
  api:
    key: ${KAKAO_API_KEY}
    url: "https://dapi.kakao.com/v2/local/search/address.json"

management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 9000