# =================================================
# AI 서버 주소 설정
# =================================================
ai:
  server:
    url: ${AI_SERVER_URL:http://localhost:8001}
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:activity-server;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# =================================================
# Spring Boot 기본 설정
# =================================================

  profiles:
    active: ${PROFILE}
  application:
    name: K-Rangers-Backend
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4.1-nano-2025-04-14
  # --- 핵심 추가: MySQL 데이터베이스 설정 ---
  datasource:
    # --- 핵심 수정: allowPublicKeyRetrieval=true 옵션 추가 ---
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?createDatabaseIfNotExists=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop # 개발 단계에서는 'update'를 사용하고, 운영 시에는 'none' 또는 'validate'를 권장합니다.
    show-sql: true # SQL 쿼리를 콘솔에 출력할지 여부
    properties:
      hibernate:
        format_sql: true # SQL 쿼리 포맷팅
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL 8 다이얼렉트 사용

kakao:
  api:
    key: ${KAKAO_API_KEY}
    url: "https://dapi.kakao.com/v2/local/search/address.json"

management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 9000
