spring:
  config:
    import: "optional:dotenv:.env"
  datasource:
    url: "jdbc:h2:~/k-rangers;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;"
    username: steve
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: true
  h2:
    console:
      enabled: true
      path: /h2-console
