name: Deploy Server

on:
  push:
    branches: [ main ]
    paths:
      - 'Backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/gamja/K-Rangers
            git pull origin main
            
            cd Backend
            docker stop travel || true
            docker rm travel || true
            docker rmi travel || true
            docker build -t travel .
            docker run -d -p 9000:9000 --network gamjanet --name travel travel
                        
            docker builder prune -f
